name: Upload YouTube Video

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'    # كل 15 دقيقة

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install axios cheerio fs-extra googleapis puppeteer

      - name: Install FFmpeg and wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg wkhtmltopdf xvfb
          ffmpeg -version
          wkhtmltoimage --version

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get install -y \
            libgbm-dev \
            libxkbcommon-x11-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcairo2

      - name: Run Upload Script
        run: node YT_Publish.js
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
